In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_pickle('predictionResults.pcl')

In [3]:
df

                                                                          y  \
1075 2016-01-01 00:00:00  2016-01-01 00:00:00    60.707199
2016-01-01 01...
     2016-01-01 01:00:00  2016-01-01 01:00:00    79.721919
2016-01-01 02...
     2016-01-01 02:00:00  2016-01-01 02:00:00    90.698524
2016-01-01 03...
     2016-01-01 03:00:00  2016-01-01 03:00:00    89.681292
2016-01-01 04...
     2016-01-01 04:00:00  2016-01-01 04:00:00    31.673040
2016-01-01 05...
     2016-01-01 05:00:00                                                NaN
     2016-01-01 06:00:00                                                NaN
     2016-01-01 07:00:00                                                NaN
     2016-01-01 08:00:00                                                NaN
     2016-01-01 09:00:00                                                NaN
     2016-01-01 10:00:00                                                NaN
     2016-01-01 11:00:00                                                NaN
     2016-01-01 12:00:00                                                NaN
     2016-01-01 13:00:00                                                NaN
     2016-01-01 14:00:00                                                NaN
     2016-01-01 15:00:00                                                NaN
     2016-01-01 16:00:00                                                NaN
     2016-01-01 17:00:00                                                NaN
     2016-01-01 18:00:00                                                NaN
     2016-01-01 19:00:00                                                NaN
     2016-01-01 20:00:00                                                NaN
     2016-01-01 21:00:00                                                NaN
     2016-01-01 22:00:00                                                NaN
     2016-01-01 23:00:00                                                NaN
     2016-01-02 00:00:00                                                NaN
     2016-01-02 01:00:00                                                NaN
     2016-01-02 02:00:00                                                NaN
     2016-01-02 03:00:00                                                NaN
     2016-01-02 04:00:00                                                NaN
     2016-01-02 05:00:00                                                NaN
...                                                                     ...
2168 2016-05-28 19:00:00                                                NaN
     2016-05-28 20:00:00                                                NaN
     2016-05-28 21:00:00                                                NaN
     2016-05-28 22:00:00                                                NaN
     2016-05-28 23:00:00                                                NaN
     2016-05-29 00:00:00                                                NaN
     2016-05-29 01:00:00                                                NaN
     2016-05-29 02:00:00                                                NaN
     2016-05-29 03:00:00                                                NaN
     2016-05-29 04:00:00                                                NaN
     2016-05-29 05:00:00                                                NaN
     2016-05-29 06:00:00                                                NaN
     2016-05-29 07:00:00                                                NaN
     2016-05-29 08:00:00                                                NaN
     2016-05-29 09:00:00                                                NaN
     2016-05-29 10:00:00                                                NaN
     2016-05-29 11:00:00                                                NaN
     2016-05-29 12:00:00                                                NaN
     2016-05-29 13:00:00                                                NaN
     2016-05-29 14:00:00                                                NaN
     2016-05-29 15:00:00                                                NaN
     2016-05-29 16:00:00                                                NaN
     2016-05-29 17:00:00                                                NaN
     2016-05-29 18:00:00                                                NaN
     2016-05-29 19:00:00                                                NaN
     2016-05-29 20:00:00                                                NaN
     2016-05-29 21:00:00                                                NaN
     2016-05-29 22:00:00                                                NaN
     2016-05-29 23:00:00                                                NaN
     2016-05-30 00:00:00                                                NaN

                              err
1075 2016-01-01 00:00:00  31.8616
     2016-01-01 01:00:00  43.7103
     2016-01-01 02:00:00  61.0409
     2016-01-01 03:00:00  72.0109
     2016-01-01 04:00:00  15.6732
     2016-01-01 05:00:00      NaN
     2016-01-01 06:00:00      NaN
     2016-01-01 07:00:00      NaN
     2016-01-01 08:00:00      NaN
     2016-01-01 09:00:00      NaN
     2016-01-01 10:00:00      NaN
     2016-01-01 11:00:00      NaN
     2016-01-01 12:00:00      NaN
     2016-01-01 13:00:00      NaN
     2016-01-01 14:00:00      NaN
     2016-01-01 15:00:00      NaN
     2016-01-01 16:00:00      NaN
     2016-01-01 17:00:00      NaN
     2016-01-01 18:00:00      NaN
     2016-01-01 19:00:00      NaN
     2016-01-01 20:00:00      NaN
     2016-01-01 21:00:00      NaN
     2016-01-01 22:00:00      NaN
     2016-01-01 23:00:00      NaN
     2016-01-02 00:00:00      NaN
     2016-01-02 01:00:00      NaN
     2016-01-02 02:00:00      NaN
     2016-01-02 03:00:00      NaN
     2016-01-02 04:00:00      NaN
     2016-01-02 05:00:00      NaN
...                           ...
2168 2016-05-28 19:00:00      NaN
     2016-05-28 20:00:00      NaN
     2016-05-28 21:00:00      NaN
     2016-05-28 22:00:00      NaN
     2016-05-28 23:00:00      NaN
     2016-05-29 00:00:00      NaN
     2016-05-29 01:00:00      NaN
     2016-05-29 02:00:00      NaN
     2016-05-29 03:00:00      NaN
     2016-05-29 04:00:00      NaN
     2016-05-29 05:00:00      NaN
     2016-05-29 06:00:00      NaN
     2016-05-29 07:00:00      NaN
     2016-05-29 08:00:00      NaN
     2016-05-29 09:00:00      NaN
     2016-05-29 10:00:00      NaN
     2016-05-29 11:00:00      NaN
     2016-05-29 12:00:00      NaN
     2016-05-29 13:00:00      NaN
     2016-05-29 14:00:00      NaN
     2016-05-29 15:00:00      NaN
     2016-05-29 16:00:00      NaN
     2016-05-29 17:00:00      NaN
     2016-05-29 18:00:00      NaN
     2016-05-29 19:00:00      NaN
     2016-05-29 20:00:00      NaN
     2016-05-29 21:00:00      NaN
     2016-05-29 22:00:00      NaN
     2016-05-29 23:00:00      NaN
     2016-05-30 00:00:00      NaN

[367302 rows x 2 columns]